### ISSUE TITLE
Fails to compile with hpqtypes-1.13.0.0

### ISSUE THREAD

**Issue by alaendle** [scrive/hpqtypes-extras#129]
```
Preprocessing library for hpqtypes-extras-1.18.0.0...
       Building library for hpqtypes-extras-1.18.0.0...
       [21 of 21] Compiling Database.PostgreSQL.PQTypes.Checks
       /home/curators/work/unpack-dir/unpacked/hpqtypes-extras-1.18.0.0-f5c1ce3970fbf99ef372723ac9b13649452a83e32b79b652d3f4bd55dd4693cf/src/Database/PostgreSQL/PQTypes/Checks.hs:858:22: error: [GHC-88464]
           Variable not in scope: tsAutoTransaction :: a0 -> Bool
           |
       858 |   autoTransaction <- tsAutoTransaction <$> getTransactionSettings
           |                      ^^^^^^^^^^^^^^^^^

       /home/curators/work/unpack-dir/unpacked/hpqtypes-extras-1.18.0.0-f5c1ce3970fbf99ef372723ac9b13649452a83e32b79b652d3f4bd55dd4693cf/src/Database/PostgreSQL/PQTypes/Checks.hs:858:44: error: [GHC-88464]
           Variable not in scope: getTransactionSettings :: m a0
           Suggested fix:
             Perhaps use one of these:
               data constructor ‘TransactionSettings’ (imported from Database.PostgreSQL.PQTypes),
               ‘defaultTransactionSettings’ (imported from Database.PostgreSQL.PQTypes)
           |
       858 |   autoTransaction <- tsAutoTransaction <$> getTransactionSettings
           |                                            ^^^^^^^^^^^^^^^^^^^^^^
```

Disable text extra package for now on stackage.
(fyi @jsynacek)

**Comment by alaendle** [comment]
Btw, same is true for the `consumers` package.
